In [1]:
import torch
import torch.nn as nn

In [12]:
#input
torch.manual_seed(42) # same as random_features
inputs = torch.tensor([1.0 , 2.0 , 3.0])

In [13]:
neuron = nn.Linear(in_features = 3 , out_features = 1)

In [14]:
output = neuron(inputs)

In [15]:
output


tensor([1.5244], grad_fn=<ViewBackward0>)

In [16]:
# To check weight
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [17]:
# To check bias
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [18]:
# verification by formula
# output --> Summation(WiXi) + bias
# WiXi means Weight and features dot product dot product in ML --> @
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)